### PR TITLE
Function transformer

### PR DESCRIPTION
**Pull request by qtux**
Hi David,

as promised in #13, here is the generic FunctionTransformer for applying functions to Xt. Resampling Xt is disallowed and y not changed (and not provided to the supplied function).

Cheers,
Matthias

### CODE REVIEW

**Comment by dmbee** [comment]
This looks great Matthias. Very useful contribution. I will test out and merge it Monday. 

Thanks
David

**Comment by dmbee** [comment]
Matthias, 

One issue with this - it should use TransformerMixin as the base class and follow that API. FeatureRep for instance also follows the TransformerMixin API.

Since y is not modified, it FunctionTransformer should not inherit from XyTransformerMixin. 

Please fix and resubmit the pull request. 
Thank you
David

**Comment by qtux** [comment]
I fixed it and rebased this PR.

Cheers,
Matthias

**Comment by dmbee** [comment]
Thanks Matthias - I merged your work. I moved the example to the API reference, because I thought it was concise enough to fit there. 

Great stuff. Thank you. 
David

**Pull request merged**
