### PR TITLE
doc: Fix overlap parameter description

### PR DESCRIPTION
**Pull request by qtux**
Change from "0 <= overlap < 1" to "0 <= overlap <= 1"

### CODE REVIEW

**Comment by dmbee** [comment]
Hi Matthias, thanks for your pull request. 

Setting overlap to 1.0 results in the segments being advanced by a single sample. Perhaps I should just document that behavior? As it may be useful in some cases to do this...

Thoughts?

David

**Comment by qtux** [comment]
Hi David,

I think that is a good idea, I found it to be very useful to set overlap to 1.0 without the need to calculate the exact segment size. I added your comment to the documentation.

Cheers,
Matthias

**Comment by qtux** [comment]
PS: I added another commit to fix some typos.

**Comment by dmbee** [comment]
Thanks for your help on this Matthias.

**Pull request merged**
